# ==============================================================================
# Merged Lakeflow Source: monday
# ==============================================================================
# This file is auto-generated by scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from datetime import datetime, timedelta
from decimal import Decimal
from typing import Any, Iterator, Optional
import time

from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # libs/utils.py
    ########################################################

    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None
        # Handle complex types
        if isinstance(field_type, StructType):
            # Validate input for StructType
            if not isinstance(value, dict):
                raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
            # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
            if value == {}:
                raise ValueError(
                    f"field in StructType cannot be an empty dict. Please assign None as the default value instead."
                )
            # For StructType, recursively parse fields into a Row
            field_dict = {}
            for field in field_type.fields:
                # When a field does not exist in the input:
                # 1. set it to None when schema marks it as nullable
                # 2. Otherwise, raise an error.
                if field.name in value:
                    field_dict[field.name] = parse_value(
                        value.get(field.name), field.dataType
                    )
                elif field.nullable:
                    field_dict[field.name] = None
                else:
                    raise ValueError(
                        f"Field {field.name} is not nullable but not found in the input"
                    )

            return Row(**field_dict)
        elif isinstance(field_type, ArrayType):
            # For ArrayType, parse each element in the array
            if not isinstance(value, list):
                # Handle edge case: single value that should be an array
                if field_type.containsNull:
                    # Try to convert to a single-element array if nulls are allowed
                    return [parse_value(value, field_type.elementType)]
                else:
                    raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
            return [parse_value(v, field_type.elementType) for v in value]
        elif isinstance(field_type, MapType):
            # Handle MapType - new support
            if not isinstance(value, dict):
                raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
            return {
                parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
                for k, v in value.items()
            }
        # Handle primitive types with more robust error handling and type conversion
        try:
            if isinstance(field_type, StringType):
                # Don't convert None to "None" string
                return str(value) if value is not None else None
            elif isinstance(field_type, (IntegerType, LongType)):
                # Convert numeric strings and floats to integers
                if isinstance(value, str) and value.strip():
                    # Handle numeric strings
                    if "." in value:
                        return int(float(value))
                    return int(value)
                elif isinstance(value, (int, float)):
                    return int(value)
                raise ValueError(f"Cannot convert {value} to integer")
            elif isinstance(field_type, FloatType) or isinstance(field_type, DoubleType):
                # New support for floating point types
                if isinstance(value, str) and value.strip():
                    return float(value)
                return float(value)
            elif isinstance(field_type, DecimalType):
                # New support for Decimal type

                if isinstance(value, str) and value.strip():
                    return Decimal(value)
                return Decimal(str(value))
            elif isinstance(field_type, BooleanType):
                # Enhanced boolean conversion
                if isinstance(value, str):
                    lowered = value.lower()
                    if lowered in ("true", "t", "yes", "y", "1"):
                        return True
                    elif lowered in ("false", "f", "no", "n", "0"):
                        return False
                return bool(value)
            elif isinstance(field_type, DateType):
                # New support for DateType
                if isinstance(value, str):
                    # Try multiple date formats
                    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                        try:
                            return datetime.strptime(value, fmt).date()
                        except ValueError:
                            continue
                    # ISO format as fallback
                    return datetime.fromisoformat(value).date()
                elif isinstance(value, datetime):
                    return value.date()
                raise ValueError(f"Cannot convert {value} to date")
            elif isinstance(field_type, TimestampType):
                # Enhanced timestamp handling
                if isinstance(value, str):
                    # Handle multiple timestamp formats including Z and timezone offsets
                    if value.endswith("Z"):
                        value = value.replace("Z", "+00:00")
                    try:
                        return datetime.fromisoformat(value)
                    except ValueError:
                        # Try additional formats if ISO format fails
                        for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                            try:
                                return datetime.strptime(value, fmt)
                            except ValueError:
                                continue
                elif isinstance(value, (int, float)):
                    # Handle Unix timestamps
                    return datetime.fromtimestamp(value)
                elif isinstance(value, datetime):
                    return value
                raise ValueError(f"Cannot convert {value} to timestamp")
            else:
                # Check for custom UDT handling
                if hasattr(field_type, "fromJson"):
                    # Support for User Defined Types that implement fromJson
                    return field_type.fromJson(value)
                raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            # Add context to the error
            raise ValueError(
                f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}"
            )


    ########################################################
    # libs/graphql_utils.py
    ########################################################

    GraphQL utilities for Lakeflow connectors.

    Provides lightweight GraphQL client built on requests library,
    following the same patterns as existing REST API connectors.
    """

    import requests
    import time
    from typing import Any, Optional


    class GraphQLClient:
        """
        Lightweight GraphQL client using requests library.

        Provides GraphQL query execution with error handling, retries,
        and rate limiting support.
        """

        def __init__(self, endpoint: str, headers: dict[str, str]):
            """
            Initialize GraphQL client.

            Args:
                endpoint: GraphQL API endpoint URL
                headers: HTTP headers including authorization
            """
            self.endpoint = endpoint
            self.headers = headers

        def execute(
            self, query: str, variables: Optional[dict[str, Any]] = None
        ) -> dict[str, Any]:
            """
            Execute a GraphQL query or mutation.

            Args:
                query: GraphQL query or mutation string
                variables: Optional variables for the query

            Returns:
                Response data as dictionary

            Raises:
                GraphQLError: If GraphQL returns errors
                RuntimeError: If HTTP request fails
            """
            payload = {"query": query}
            if variables:
                payload["variables"] = variables

            response = requests.post(
                self.endpoint, json=payload, headers=self.headers, timeout=30
            )

            if response.status_code != 200:
                raise RuntimeError(
                    f"GraphQL HTTP error: {response.status_code} {response.text}"
                )

            result = response.json()

            # GraphQL returns 200 even with errors - check errors in response
            handle_graphql_errors(result)

            return result

        def execute_with_retry(
            self,
            query: str,
            variables: Optional[dict[str, Any]] = None,
            max_retries: int = 3,
            backoff_factor: float = 2.0,
        ) -> dict[str, Any]:
            """
            Execute a GraphQL query with exponential backoff retry.

            Args:
                query: GraphQL query or mutation string
                variables: Optional variables for the query
                max_retries: Maximum number of retry attempts
                backoff_factor: Multiplier for exponential backoff

            Returns:
                Response data as dictionary

            Raises:
                GraphQLError: If GraphQL returns errors after all retries
                RuntimeError: If HTTP request fails after all retries
            """
            last_exception = None

            for attempt in range(max_retries + 1):
                try:
                    return self.execute(query, variables)
                except (RuntimeError, requests.exceptions.RequestException) as e:
                    last_exception = e
                    if attempt < max_retries:
                        wait_time = backoff_factor**attempt
                        time.sleep(wait_time)
                        continue
                    # Last attempt failed
                    break

            # All retries exhausted
            raise RuntimeError(
                f"GraphQL request failed after {max_retries} retries: {last_exception}"
            )


    class GraphQLError(Exception):
        """Exception raised for GraphQL errors."""

        def __init__(self, errors: list[dict[str, Any]]):
            self.errors = errors
            error_messages = [e.get("message", str(e)) for e in errors]
            super().__init__(f"GraphQL errors: {'; '.join(error_messages)}")


    def handle_graphql_errors(response: dict[str, Any]) -> None:
        """
        Parse GraphQL response and raise exception if errors exist.

        GraphQL APIs return 200 status code even when there are errors,
        with errors included in the response body.

        Args:
            response: GraphQL response dictionary

        Raises:
            GraphQLError: If response contains errors
        """
        if "errors" in response and response["errors"]:
            raise GraphQLError(response["errors"])


    def extract_cursor(response: dict[str, Any], path: list[str]) -> Optional[str]:
        """
        Extract cursor value from nested GraphQL response.

        Helper function to navigate nested response structure and
        extract pagination cursor.

        Args:
            response: GraphQL response dictionary
            path: List of keys to navigate (e.g., ["data", "items", "cursor"])

        Returns:
            Cursor value as string, or None if not found

        Example:
            cursor = extract_cursor(response, ["data", "boards", "pageInfo", "endCursor"])
        """
        current = response
        for key in path:
            if not isinstance(current, dict) or key not in current:
                return None
            current = current[key]
        return str(current) if current is not None else None


    def build_pagination_variables(
        page: int = 1, limit: int = 50, cursor: Optional[str] = None
    ) -> dict[str, Any]:
        """
        Build common pagination variables for GraphQL queries.

        Args:
            page: Page number (for page-based pagination)
            limit: Number of items per page
            cursor: Cursor value (for cursor-based pagination)

        Returns:
            Variables dictionary for GraphQL query

        Example:
            variables = build_pagination_variables(page=2, limit=25)
            # Returns: {"page": 2, "limit": 25}
        """
        variables = {"page": page, "limit": limit}
        if cursor:
            variables["cursor"] = cursor
        return variables


    ########################################################
    # sources/monday/monday.py
    ########################################################

    try:
        from libs.graphql_utils import GraphQLClient, GraphQLError
    except ImportError:
        # For development/testing before merge
        import sys
        import os

        sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))
        from libs.graphql_utils import GraphQLClient, GraphQLError


    class LakeflowConnect:
        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the Monday.com connector with connection-level options.

            Expected options:
                - api_key: Monday.com API key for authentication.
            """
            api_key = options.get("api_key")
            if not api_key:
                raise ValueError("Monday.com connector requires 'api_key' in options")

            self.api_key = api_key

            # Initialize GraphQL client
            self._graphql_client = GraphQLClient(
                endpoint="https://api.monday.com/v2",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
            )

        def list_tables(self) -> list[str]:
            """
            List names of all tables supported by this connector.

            Priority 1: Core objects
            Priority 2: Relational data
            Priority 3: Extended features
            """
            return [
                # Priority 1: Core objects
                "boards",
                "items",
                "users",
                "teams",
                "workspaces",
                # Priority 2: Relational data
                "updates",
                "columns",
                "groups",
                # Priority 3: Extended
                "tags",
                "activity_logs",
            ]

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.

            Schemas are static and derived from Monday.com GraphQL API documentation.
            Core fields are typed, variable data (like column_values) uses MapType.
            """
            schemas = {
                "boards": self._get_boards_schema(),
                "items": self._get_items_schema(),
                "users": self._get_users_schema(),
                "teams": self._get_teams_schema(),
                "workspaces": self._get_workspaces_schema(),
                "updates": self._get_updates_schema(),
                "columns": self._get_columns_schema(),
                "groups": self._get_groups_schema(),
                "tags": self._get_tags_schema(),
                "activity_logs": self._get_activity_logs_schema(),
            }

            if table_name not in schemas:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {', '.join(schemas.keys())}"
                )

            return schemas[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.

            Returns primary keys, cursor field for CDC, and ingestion type.
            """
            metadata_map = {
                "boards": {
                    "primary_keys": ["id"],
                    "cursor_field": "updated_at",
                    "ingestion_type": "cdc",
                },
                "items": {
                    "primary_keys": ["id"],
                    "cursor_field": "updated_at",
                    "ingestion_type": "cdc",
                },
                "users": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                },
                "teams": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                },
                "workspaces": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                },
                "updates": {
                    "primary_keys": ["id"],
                    "cursor_field": "updated_at",
                    "ingestion_type": "cdc",
                },
                "columns": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                },
                "groups": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                },
                "tags": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                },
                "activity_logs": {
                    "primary_keys": ["id"],
                    "cursor_field": "created_at",
                    "ingestion_type": "append",
                },
            }

            if table_name not in metadata_map:
                raise ValueError(
                    f"Table '{table_name}' metadata not found. "
                    f"Supported tables: {', '.join(metadata_map.keys())}"
                )

            return metadata_map[table_name]

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the records of a table and return an iterator of records and an offset.

            Supports incremental loading for CDC tables using updated_at cursor.
            Supports pagination for large datasets.
            """
            read_methods = {
                "boards": self._read_boards,
                "items": self._read_items,
                "users": self._read_users,
                "teams": self._read_teams,
                "workspaces": self._read_workspaces,
                "updates": self._read_updates,
                "columns": self._read_columns,
                "groups": self._read_groups,
                "tags": self._read_tags,
                "activity_logs": self._read_activity_logs,
            }

            if table_name not in read_methods:
                raise ValueError(
                    f"Table '{table_name}' read method not implemented. "
                    f"Supported tables: {', '.join(read_methods.keys())}"
                )

            return read_methods[table_name](start_offset, table_options)

        # Schema Definitions

        def _get_boards_schema(self) -> StructType:
            """Schema for boards table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("name", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("state", StringType(), True),
                    StructField("board_kind", StringType(), True),
                    StructField("created_at", StringType(), True),
                    StructField("updated_at", StringType(), True),
                    StructField("workspace_id", StringType(), True),
                    StructField("owner_id", StringType(), True),
                    StructField(
                        "groups",
                        ArrayType(MapType(StringType(), StringType())),
                        True,
                    ),
                    StructField(
                        "columns",
                        ArrayType(MapType(StringType(), StringType())),
                        True,
                    ),
                ]
            )

        def _get_items_schema(self) -> StructType:
            """Schema for items table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("name", StringType(), True),
                    StructField("board_id", StringType(), True),
                    StructField("group_id", StringType(), True),
                    StructField("state", StringType(), True),
                    StructField("created_at", StringType(), True),
                    StructField("updated_at", StringType(), True),
                    StructField("creator_id", StringType(), True),
                    StructField(
                        "column_values",
                        ArrayType(
                            StructType(
                                [
                                    StructField("id", StringType(), True),
                                    StructField("column_id", StringType(), True),
                                    StructField("type", StringType(), True),
                                    StructField("text", StringType(), True),
                                    StructField("value", StringType(), True),
                                ]
                            )
                        ),
                        True,
                    ),
                ]
            )

        def _get_users_schema(self) -> StructType:
            """Schema for users table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("name", StringType(), True),
                    StructField("email", StringType(), True),
                    StructField("url", StringType(), True),
                    StructField("title", StringType(), True),
                    StructField("created_at", StringType(), True),
                    StructField("birthday", StringType(), True),
                    StructField("country_code", StringType(), True),
                    StructField("location", StringType(), True),
                    StructField("time_zone_identifier", StringType(), True),
                    StructField("is_guest", BooleanType(), True),
                    StructField("is_pending", BooleanType(), True),
                    StructField("enabled", BooleanType(), True),
                    StructField("photo_thumb", StringType(), True),
                ]
            )

        def _get_teams_schema(self) -> StructType:
            """Schema for teams table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("name", StringType(), True),
                    StructField("picture_url", StringType(), True),
                    StructField(
                        "users",
                        ArrayType(MapType(StringType(), StringType())),
                        True,
                    ),
                ]
            )

        def _get_workspaces_schema(self) -> StructType:
            """Schema for workspaces table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("name", StringType(), True),
                    StructField("kind", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("created_at", StringType(), True),
                ]
            )

        def _get_updates_schema(self) -> StructType:
            """Schema for updates table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("item_id", StringType(), True),
                    StructField("creator_id", StringType(), True),
                    StructField("body", StringType(), True),
                    StructField("text_body", StringType(), True),
                    StructField("created_at", StringType(), True),
                    StructField("updated_at", StringType(), True),
                ]
            )

        def _get_columns_schema(self) -> StructType:
            """Schema for columns table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("title", StringType(), True),
                    StructField("type", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("board_id", StringType(), True),
                    StructField("width", LongType(), True),
                    StructField("settings_str", StringType(), True),
                ]
            )

        def _get_groups_schema(self) -> StructType:
            """Schema for groups table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("title", StringType(), True),
                    StructField("color", StringType(), True),
                    StructField("position", StringType(), True),
                    StructField("board_id", StringType(), True),
                ]
            )

        def _get_tags_schema(self) -> StructType:
            """Schema for tags table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("name", StringType(), True),
                    StructField("color", StringType(), True),
                ]
            )

        def _get_activity_logs_schema(self) -> StructType:
            """Schema for activity_logs table."""
            return StructType(
                [
                    StructField("id", StringType(), False),
                    StructField("event", StringType(), True),
                    StructField("user_id", StringType(), True),
                    StructField("account_id", StringType(), True),
                    StructField("created_at", StringType(), True),
                    StructField("data", StringType(), True),
                    StructField("entity", StringType(), True),
                ]
            )

        # Read Methods

        def _read_boards(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read boards table with pagination and CDC support."""
            page = 1
            if start_offset and isinstance(start_offset, dict):
                page = start_offset.get("page", 1)

            limit = int(table_options.get("limit", 50))
            max_pages = int(table_options.get("max_pages_per_batch", 50))

            query = """
            query GetBoards($page: Int!, $limit: Int!) {
              boards(page: $page, limit: $limit, order_by: updated_at) {
                id
                name
                description
                state
                board_kind
                created_at
                updated_at
                workspace {
                  id
                }
                owner {
                  id
                }
                groups {
                  id
                  title
                  color
                  position
                }
                columns {
                  id
                  title
                  type
                  description
                  width
                  settings_str
                }
              }
            }
            """

            all_records = []
            pages_fetched = 0

            while pages_fetched < max_pages:
                variables = {"page": page, "limit": limit}

                try:
                    response = self._graphql_client.execute(query, variables)
                except GraphQLError as e:
                    raise RuntimeError(f"Monday.com API error for boards: {e}")

                boards = response.get("data", {}).get("boards", [])

                if not boards:
                    break

                # Transform boards to match schema
                for board in boards:
                    record = {
                        "id": str(board.get("id", "")),
                        "name": board.get("name"),
                        "description": board.get("description"),
                        "state": board.get("state"),
                        "board_kind": board.get("board_kind"),
                        "created_at": board.get("created_at"),
                        "updated_at": board.get("updated_at"),
                        "workspace_id": self._extract_id(board.get("workspace")),
                        "owner_id": self._extract_id(board.get("owner")),
                        "groups": self._transform_nested_list(board.get("groups", [])),
                        "columns": self._transform_nested_list(board.get("columns", [])),
                    }
                    all_records.append(record)

                page += 1
                pages_fetched += 1

                # Rate limiting
                time.sleep(0.2)

            next_offset = {"page": page}
            return iter(all_records), next_offset

        def _read_items(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read items table with pagination and CDC support."""
            # Get board IDs from table options
            board_ids_str = table_options.get("board_ids")
            if not board_ids_str:
                raise ValueError("items table requires 'board_ids' in table_options")

            board_ids = [bid.strip() for bid in board_ids_str.split(",")]

            limit = int(table_options.get("limit", 50))
            max_pages = int(table_options.get("max_pages_per_batch", 50))

            # Track offset per board
            if start_offset and isinstance(start_offset, dict):
                current_board_idx = start_offset.get("board_idx", 0)
                page = start_offset.get("page", 1)
            else:
                current_board_idx = 0
                page = 1

            all_records = []
            pages_fetched = 0

            # Iterate through boards
            while current_board_idx < len(board_ids) and pages_fetched < max_pages:
                board_id = board_ids[current_board_idx]

                query = """
                query GetItems($boardId: [Int!]!, $page: Int!, $limit: Int!) {
                  boards(ids: $boardId) {
                    id
                    items_page(limit: $limit, query_params: {page: $page}) {
                      items {
                        id
                        name
                        state
                        created_at
                        updated_at
                        creator {
                          id
                        }
                        group {
                          id
                        }
                        column_values {
                          id
                          column {
                            id
                          }
                          type
                          text
                          value
                        }
                      }
                    }
                  }
                }
                """

                variables = {"boardId": [int(board_id)], "page": page, "limit": limit}

                try:
                    response = self._graphql_client.execute(query, variables)
                except GraphQLError as e:
                    raise RuntimeError(f"Monday.com API error for items: {e}")

                boards_data = response.get("data", {}).get("boards", [])
                if not boards_data:
                    # Move to next board
                    current_board_idx += 1
                    page = 1
                    continue

                items = boards_data[0].get("items_page", {}).get("items", [])

                if not items:
                    # Move to next board
                    current_board_idx += 1
                    page = 1
                    continue

                # Transform items to match schema
                for item in items:
                    column_values = []
                    for cv in item.get("column_values", []):
                        column_values.append(
                            {
                                "id": str(cv.get("id", "")),
                                "column_id": self._extract_id(cv.get("column")),
                                "type": cv.get("type"),
                                "text": cv.get("text"),
                                "value": cv.get("value"),
                            }
                        )

                    record = {
                        "id": str(item.get("id", "")),
                        "name": item.get("name"),
                        "board_id": board_id,
                        "group_id": self._extract_id(item.get("group")),
                        "state": item.get("state"),
                        "created_at": item.get("created_at"),
                        "updated_at": item.get("updated_at"),
                        "creator_id": self._extract_id(item.get("creator")),
                        "column_values": column_values,
                    }
                    all_records.append(record)

                page += 1
                pages_fetched += 1

                # Rate limiting
                time.sleep(0.2)

            next_offset = {"board_idx": current_board_idx, "page": page}
            return iter(all_records), next_offset

        def _read_users(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read users table (snapshot mode)."""
            query = """
            query GetUsers {
              users {
                id
                name
                email
                url
                title
                created_at
                birthday
                country_code
                location
                time_zone_identifier
                is_guest
                is_pending
                enabled
                photo_thumb
              }
            }
            """

            try:
                response = self._graphql_client.execute(query)
            except GraphQLError as e:
                raise RuntimeError(f"Monday.com API error for users: {e}")

            users = response.get("data", {}).get("users", [])

            records = []
            for user in users:
                record = {
                    "id": str(user.get("id", "")),
                    "name": user.get("name"),
                    "email": user.get("email"),
                    "url": user.get("url"),
                    "title": user.get("title"),
                    "created_at": user.get("created_at"),
                    "birthday": user.get("birthday"),
                    "country_code": user.get("country_code"),
                    "location": user.get("location"),
                    "time_zone_identifier": user.get("time_zone_identifier"),
                    "is_guest": user.get("is_guest"),
                    "is_pending": user.get("is_pending"),
                    "enabled": user.get("enabled"),
                    "photo_thumb": user.get("photo_thumb"),
                }
                records.append(record)

            # Snapshot mode - no meaningful offset
            return iter(records), {}

        def _read_teams(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read teams table (snapshot mode)."""
            query = """
            query GetTeams {
              teams {
                id
                name
                picture_url
                users {
                  id
                  name
                  email
                }
              }
            }
            """

            try:
                response = self._graphql_client.execute(query)
            except GraphQLError as e:
                raise RuntimeError(f"Monday.com API error for teams: {e}")

            teams = response.get("data", {}).get("teams", [])

            records = []
            for team in teams:
                record = {
                    "id": str(team.get("id", "")),
                    "name": team.get("name"),
                    "picture_url": team.get("picture_url"),
                    "users": self._transform_nested_list(team.get("users", [])),
                }
                records.append(record)

            return iter(records), {}

        def _read_workspaces(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read workspaces table (snapshot mode)."""
            query = """
            query GetWorkspaces {
              workspaces {
                id
                name
                kind
                description
                created_at
              }
            }
            """

            try:
                response = self._graphql_client.execute(query)
            except GraphQLError as e:
                raise RuntimeError(f"Monday.com API error for workspaces: {e}")

            workspaces = response.get("data", {}).get("workspaces", [])

            records = []
            for workspace in workspaces:
                record = {
                    "id": str(workspace.get("id", "")),
                    "name": workspace.get("name"),
                    "kind": workspace.get("kind"),
                    "description": workspace.get("description"),
                    "created_at": workspace.get("created_at"),
                }
                records.append(record)

            return iter(records), {}

        def _read_updates(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read updates table with CDC support."""
            # Updates require board IDs or can fetch from items
            board_ids_str = table_options.get("board_ids")
            if not board_ids_str:
                raise ValueError("updates table requires 'board_ids' in table_options")

            board_ids = [bid.strip() for bid in board_ids_str.split(",")]

            # Track offset per board
            if start_offset and isinstance(start_offset, dict):
                current_board_idx = start_offset.get("board_idx", 0)
                page = start_offset.get("page", 1)
            else:
                current_board_idx = 0
                page = 1

            limit = int(table_options.get("limit", 50))
            max_pages = int(table_options.get("max_pages_per_batch", 50))

            all_records = []
            pages_fetched = 0

            # Iterate through boards to get updates
            while current_board_idx < len(board_ids) and pages_fetched < max_pages:
                board_id = board_ids[current_board_idx]

                query = """
                query GetUpdates($boardId: [Int!]!, $page: Int!, $limit: Int!) {
                  boards(ids: $boardId) {
                    updates(page: $page, limit: $limit) {
                      id
                      item_id
                      creator {
                        id
                      }
                      body
                      text_body
                      created_at
                      updated_at
                    }
                  }
                }
                """

                variables = {"boardId": [int(board_id)], "page": page, "limit": limit}

                try:
                    response = self._graphql_client.execute(query, variables)
                except GraphQLError as e:
                    raise RuntimeError(f"Monday.com API error for updates: {e}")

                boards_data = response.get("data", {}).get("boards", [])
                if not boards_data:
                    current_board_idx += 1
                    page = 1
                    continue

                updates = boards_data[0].get("updates", [])

                if not updates:
                    current_board_idx += 1
                    page = 1
                    continue

                for update in updates:
                    record = {
                        "id": str(update.get("id", "")),
                        "item_id": update.get("item_id"),
                        "creator_id": self._extract_id(update.get("creator")),
                        "body": update.get("body"),
                        "text_body": update.get("text_body"),
                        "created_at": update.get("created_at"),
                        "updated_at": update.get("updated_at"),
                    }
                    all_records.append(record)

                page += 1
                pages_fetched += 1
                time.sleep(0.2)

            next_offset = {"board_idx": current_board_idx, "page": page}
            return iter(all_records), next_offset

        def _read_columns(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read columns table (extracted from boards)."""
            # Columns are board-specific, extract from boards query
            board_ids_str = table_options.get("board_ids")
            if not board_ids_str:
                raise ValueError("columns table requires 'board_ids' in table_options")

            board_ids = [int(bid.strip()) for bid in board_ids_str.split(",")]

            query = """
            query GetBoardColumns($boardIds: [Int!]!) {
              boards(ids: $boardIds) {
                id
                columns {
                  id
                  title
                  type
                  description
                  width
                  settings_str
                }
              }
            }
            """

            variables = {"boardIds": board_ids}

            try:
                response = self._graphql_client.execute(query, variables)
            except GraphQLError as e:
                raise RuntimeError(f"Monday.com API error for columns: {e}")

            boards = response.get("data", {}).get("boards", [])

            records = []
            for board in boards:
                board_id = str(board.get("id", ""))
                for column in board.get("columns", []):
                    record = {
                        "id": str(column.get("id", "")),
                        "title": column.get("title"),
                        "type": column.get("type"),
                        "description": column.get("description"),
                        "board_id": board_id,
                        "width": column.get("width"),
                        "settings_str": column.get("settings_str"),
                    }
                    records.append(record)

            return iter(records), {}

        def _read_groups(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read groups table (extracted from boards)."""
            board_ids_str = table_options.get("board_ids")
            if not board_ids_str:
                raise ValueError("groups table requires 'board_ids' in table_options")

            board_ids = [int(bid.strip()) for bid in board_ids_str.split(",")]

            query = """
            query GetBoardGroups($boardIds: [Int!]!) {
              boards(ids: $boardIds) {
                id
                groups {
                  id
                  title
                  color
                  position
                }
              }
            }
            """

            variables = {"boardIds": board_ids}

            try:
                response = self._graphql_client.execute(query, variables)
            except GraphQLError as e:
                raise RuntimeError(f"Monday.com API error for groups: {e}")

            boards = response.get("data", {}).get("boards", [])

            records = []
            for board in boards:
                board_id = str(board.get("id", ""))
                for group in board.get("groups", []):
                    record = {
                        "id": str(group.get("id", "")),
                        "title": group.get("title"),
                        "color": group.get("color"),
                        "position": group.get("position"),
                        "board_id": board_id,
                    }
                    records.append(record)

            return iter(records), {}

        def _read_tags(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read tags table (snapshot mode)."""
            query = """
            query GetTags {
              tags {
                id
                name
                color
              }
            }
            """

            try:
                response = self._graphql_client.execute(query)
            except GraphQLError as e:
                raise RuntimeError(f"Monday.com API error for tags: {e}")

            tags = response.get("data", {}).get("tags", [])

            records = []
            for tag in tags:
                record = {
                    "id": str(tag.get("id", "")),
                    "name": tag.get("name"),
                    "color": tag.get("color"),
                }
                records.append(record)

            return iter(records), {}

        def _read_activity_logs(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Read activity_logs table (append mode)."""
            # Activity logs have limited support in GraphQL API
            # This is a placeholder - actual implementation depends on API availability

            # For now, return empty
            return iter([]), {}

        # Helper Methods

        def _extract_id(self, obj: Optional[dict]) -> Optional[str]:
            """Extract ID from nested object."""
            if obj and isinstance(obj, dict):
                id_val = obj.get("id")
                return str(id_val) if id_val is not None else None
            return None

        def _transform_nested_list(self, items: list[dict]) -> list[dict[str, str]]:
            """Transform list of nested objects to list of string maps."""
            result = []
            for item in items:
                if isinstance(item, dict):
                    # Convert all values to strings
                    transformed = {k: str(v) if v is not None else None for k, v in item.items()}
                    result.append(transformed)
            return result


    ########################################################
    # pipeline/lakeflow_python_source.py
    ########################################################

    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            records, offset = self.lakeflow_connect.read_table(
                self.options["tableName"], start, self.options
            )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(table, self.options)
                all_records.append({"tableName": table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        def __init__(self, options):
            self.options = options
            self.lakeflow_connect = LakeflowConnect(options)

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options["tableName"]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField("tableName", StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                # Assuming the LakeflowConnect interface uses get_table_schema, not get_table_details
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
